### PR TITLE
Fixes for 1.39

### LINKED ISSUE #30: Skin fataling in 1.39
I'll provide a patch shortly!

### PR DESCRIPTION
**Pull request by jdlrobson**
Fixes #30

### CODE REVIEW

File: SkinDarkVector.php [hunk 1]
```diff
@@ -35,8 +35,10 @@ class SkinDarkVector extends SkinTemplate {
 	 */
 	private $darkvectorConfig;
 
-	public function __construct() {
+	public function __construct( $options = [] ) {
+		$options['bodyOnly'] = true;
```
Comment (dolfinus) [inline SkinDarkVector.php:39]: It looks like this option does not exist in 1.38 (which is current stable release):
https://github.com/wikimedia/mediawiki/blob/REL1_38/includes/skins/Skin.php#L2630
https://github.com/wikimedia/mediawiki/blob/master/includes/skins/Skin.php#L2319

So if user will install a patched version on 1.38, it will fail?

File: collapsibleTabs.js [hunk 2]
```diff
@@ -1 +1 @@
...
...expandedWidth,$moving=$(ele);data=$.collapsibleTabs.getSettings($moving);if(!data){return}expContainerSettings=$.collapsibleTabs.getSettings($(data.expandedContainer));if(!expContainerSettings){return}expContainerSettings.shifting=true;$target=$(data.expandedContainer).find("span.placeholder:first");expandedWidth=data.expandedWidth;$moving.css("position","relative").css(rtl?"right":"left",0).css("width","1px");$target.replaceWith($moving.detach().css("width","1px").data("collapsibleTabsSettings",data).animate({width:expandedWidth+"px"},"normal",function(){$(this).attr("style","display: block;");var data,expContainerSettings;data=$.collapsibleTabs.getSettings($(this));if(data){expContainerSettings=$.collapsibleTabs.getSettings($(data.expandedContainer));if(expContainerSettings){expContainerSettings.shifting=false;$.collapsibleTabs.handleResize()}}}))},calculateTabDistance:function(){var $leftTab,$rightTab,leftEnd,rightStart;if(!rtl){$leftTab=$("#left-navigation");$rightTab=$("#right-navigation")}else{$leftTab=$("#right-navigation");$rightTab=$("#left-navigation")}leftEnd=$leftTab.offset().left+$leftTab.width();rightStart=$rightTab.offset().left;return rightStart-leftEnd}}})(jQuery);
```
Comment (dolfinus) [inline collapsibleTabs.js]: What is changed in this file?

Comment (jdlrobson) [reply collapsibleTabs.js]: Can we unminify this on master branch? Then I'll rebase.

Comment (jdlrobson) [reply collapsibleTabs.js]: I've unminified it. You can see clearly the change (use of $.debounce).
This code is better unminified since presumably it will evolve with the Vector script it copies.

Comment (dolfinus) [reply collapsibleTabs.js]: Could you please rebase this PR? I've removed code minification from collapsibleTabs.js to see that was changed

File: SkinDarkVector.php (hunk 1 above)
Comment (dolfinus) [reply SkinDarkVector.php:39]: Created new branch mw-1.39 and set it as pull request target, to avoid breaking backward compatibility with MW <1.38

File: collapsibleTabs.js (hunk 2 above)
Comment (jdlrobson) [reply collapsibleTabs.js]: done

**Comment by dolfinus** [comment]
Thank you for your contribution! Merged to `mw-1.39` branch
